tasklevelup/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('task/', include("tasks.urls")),
    path('user/', include("users.urls")),
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url=reverse_lazy("list")), name="home"),
]

tasks/urls.py
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.urls import path
from tasks.views import TaskList,  TaskCreate, TaskUpdateView
# from users.views import signup



urlpatterns = [
    path("list/", TaskList.as_view(), name="list"),
    path("create/", TaskCreate.as_view(),name="create"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("list/>page=1", TaskList.as_view(), name="listpage1")
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users.views import signup



urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

tasks/models.py
from django.db import models
from django.forms import CharField
from datetime import datetime
from django.conf import settings
from datetime import timedelta

class Difficulty(models.Model):
    importance = models.CharField(max_length=100)
    expgiven = models.IntegerField()

    def __str__(self):
        return str(self.importance)

class Task(models.Model):
    def get_deadline():
        return datetime.now() + timedelta(hours=1)

    name = models.CharField(max_length=100)
    start_time = models.TimeField(auto_now_add=True, blank=True)
    due_date = models.DateTimeField(default=get_deadline)
    is_completed = models.BooleanField(null=True)
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="tasks",
        on_delete=models.SET_NULL,
        null=True,
    )
    difficulty = models.ForeignKey(Difficulty, related_name="tasks", on_delete=models.PROTECT)
    established = models.BooleanField(default=False)

    

# Create your models here.

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    exp = models.IntegerField(default=0, null=True)

tasks/views.py
from django.shortcuts import render
from users.models import User
from tasks.models import Difficulty, Task
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
# Create your views here.

class TaskList(ListView):
    model = Task
    template_name = "tasks/list.html"
    paginate_by = 10

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)
    

class TaskCreate(CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "difficulty"]
    success_url = reverse_lazy("home")
    def form_valid(self, form):
        form.instance.assignee = self.request.user
        
        return super().form_valid(form)

class TaskUpdateView(UpdateView):
    model = Task
    fields = ["is_completed"]
    success_url = reverse_lazy("home")
    
    def form_valid(self, form):
        print(form.instance.difficulty)
        if str(form.instance.difficulty) in "Very important":
            print("succes")
            self.request.user.exp += 30
            self.request.user.save()
        if str(form.instance.difficulty) in "Average":
            print("succes2")
            self.request.user.exp += 15
            self.request.user.save()
        
        return super().form_valid(form)

class BaseListView(ListView):
    model = User
    template_name = "templates/base.html"

    def get_queryset(self):
        return User.objects.filter(user=self.request.user)

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from users.models import User
from django.shortcuts import redirect
from django.urls import reverse_lazy

# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(username=username, password=password)
            user.save()
            login(request, user)
            return redirect(reverse_lazy("home"))
    else:
        form = UserCreationForm()
        context = {
            'form': form
        }
        return render(request, "registration/signup.html", context)

tasks/templates/base.html
{%load static%}
<!DOCTYPE html>
<html>

<head>
    <title>custom project</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    {% comment %} <link rel="stylesheet" type="text/css" href="css/jquery.countdown.css">  {% endcomment %}
    <link rel="stylesheet" href={% static "styles.css" %} >
    <script type="text/javascript" src="js/jquery.plugin.js"></script> 
    <script type="text/javascript" src="js/jquery.countdown.js"></script>
</head>

<body>
    <header>

        <nav>

            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'logout' %}"><button class='btn'>Logout</button></a></li>
                <li><a href="{% url 'create' %}"><button class="btn fourth"> Create Task</button></a></li>
                <li>EXP: {{user.exp}}</li>
                

            </ul>
            {% else %}
            <li><a href="{% url 'login' %}">login</a></li>
            <li><a href="{% url 'signup' %}">signup</a></li>
            {% endif %}


        </nav>

    </header>
    {% block pagination %}
    {% endblock pagination %}
    {% block content %}
    {% endblock content %}
</body>

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>Create a new task</h1>





        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create</button>
        </form>



    </div>
</main>
{% endblock %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <div>
        <h1>My Tasks</h1>
        {% if task_list %}
        <table>
            <tr>
                <th>Name</th>
                <th>Importance</th>
            </tr>
        {% for task in task_list %}
        <tr>
        <td>{{task.name}}</td> 
        <td>{{task.difficulty}}</td>
        
        {% if task.is_completed %}
                                <td>Done</td>
                            {% else %}
                            <td>
                            <p id="demo-{{task.id}}" data-task-due={{task.due_date.isoformat}}></p> 
                            <script>
                                function addHours(numOfHours, date = new Date()) {
                                date.setTime(date.getTime() + numOfHours * 60 * 60 * 1000);

                                return date;
                                }

                                // Set the date we're counting down to
                                // var countDownDate = addHours(1);
                                var countDownDate2{{task.id}} = document.getElementById("demo-{{task.id}}").dataset.taskDue
                                // Update the count down every 1 second

                                var x = setInterval(function() {
                                
                                
                                var countDownDatenew{{task.id}} = new Date(countDownDate2{{task.id}});
                                var countDownDateadded{{task.id}} = addHours(1, countDownDatenew{{task.id}});
                                var timegot{{task.id}} = countDownDatenew{{task.id}}.getTime()+ 21601000;
                                  // Get today's date and time
                                  var later{{task.id}} = new Date().getTime() + 21601000;
                                  var now = new Date().getTime();
                                
                                  // Find the distance between now and the count down date
                                  
                                  var distance = timegot{{task.id}} - now;
                                  
                                  // Time calculations for days, hours, minutes and seconds
                                  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                                  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                                  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                                //   countDownDate += hours * 5
                                  // Display the result in the element with id="demo"
                                  document.getElementById("demo-{{task.id}}").innerHTML = minutes + "m " + seconds + "s ";
                                
                                  // If the count down is finished, write some text
                                  if (minutes == 0 && seconds == 0) {
                                    clearInterval(x);
                                    document.getElementById("demo-{{task.id}}").innerHTML = "EXPIRED";
                                  }
                                }, 1000);
                                </script>
                                </td>
                                <td>
                                    <form method="post" action="{% url 'complete_task' task.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        
                                        <button class='btn-1'>Complete</button>
                                    </form>
                                </td>
                                {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <p>You have no tasks</p>
    {% endif %}

    </div>
</main>
<footer>
    <span>
        {% if page_obj.has_previous %}
        <a href=">page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        <span>
            Page {{ page_obj.number }} of {{page_obj.paginator.num_pages }}
        </span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    </span>
</footer>
{% endblock %}